### ISSUE TITLE
Repeated permissions

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1616]
In a resource that was shared with me I found the following permissions.

@alvacouch the system is not supposed to allow me to have both view and edit permissions at the same time.  @mauriel133 could this be a front end problem.  I am not sure how this came about and this was created by a user with the geohack group (I think).

![capture](https://cloud.githubusercontent.com/assets/3456833/20450146/678ea96a-adab-11e6-9040-2a56ca7bbc01.JPG)

**Comment by mauriel133** [comment]
@pkdash, this looks like an issue while populating the context variables used to render the list.

**Comment by pkdash** [comment]
@mauriel133 I can do additional checks/filtering for the relevant context variables. But I think @alvacouch 's  pending PR #1576 should fix this issue.

**Comment by alvacouch** [comment]
PR #1576 doesn't fix the issue. It makes the issue **impossible at the database level.** This doesn't mean it is not possible at the UI level for multiple reasons. 

@mauriel133 We need to collaborate on one very sticky issue that requires changes in both access control and the UI. The routines (can_)?undo_share_* must be **deleted from access control.** In the new scheme they do **erroneous and disallowed things.** You have used them in limited places. I will ensure that (can_)?share_* will do the appropriate things, and then you'll need to delete the (can_)?undo_share_* routines from the UI responders and test that everything is working. 

Will document the reason why in issue #1591.

**Comment by pkdash** [comment]
@alvacouch I thought the data migration as part of #1576 deletes those multiple privileges over the same object.

**Comment by alvacouch** [comment]
@pkdash The data migration does eliminate duplicates, but **there are other potential causes of duplicates than data.** Thus I cannot be absolutely sure that this will address the issue completely.

**Comment by pkdash** [comment]
@alvacouch If the problem doesn't go away with this data migration, I would assume the problem is either in the view function code or in the access control api function that the view function relies upon. In that case I can fix it.

**Comment by dtarb** [comment]
I am unable to find the resource that this was reproduced on.  It was not one I created, so may have been changed.  Closing.
