### ISSUE TITLE
Django constraints upon resource models are inadequate

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1645]
I can't help but notice -- as the closest thing this team has to a DBA -- that the Django models as implemented now do not utilize Django constraints effectively in preventing cruft of various kinds from entering the Django database. Problems include: 

1. Use of generic relations and soft links (GenericRelation) rather than hard constraints (ForeignKey, OneToOne, ManyToMany) to link together various kinds of data. Accordingly, the typical integrity checks for hard constraints are missing, and it is not possible to delegate these to the database system. These soft constraints are then consistently used in the code as if they were hard constraints. 
2. Improper use of loose constraints on specific items, e.g., using a list to represent a value that must be a singleton. E.g., CoreMetaData.title

What this means to the programmer is that a lot of database corruption (e.g., dangling references, unreferenced items) needs to be cleaned up in the application code, rather than being maintained by the database system. E.g., the application code has to ensure that there is only one title, while the model representation of title allows that item to be a list of several titles. Likewise, the application code has to clean up after deletion of the source side of a soft link, rather than the database doing that for the programmer.  

This is difficult -- but not impossible -- to fix. It requires some data migrations to tighten the constraints, followed by turning over the cleanup to the database system and deleting it from the code. Surprisingly, it would not require many code changes; much of the code won't change just because constraints are being tightened (though some code bugs might show up if the UI tries to do something that shouldn't be allowed)! 

(also, we need to remove the geoanalytics dependencies that were the reason for this soft structure, which we aren' t using)
 
The net result would be a substantive reduction in code complexity and maintenance.

**Comment by alvacouch** [comment]
There is another major benefit, which is that native Django management becomes available for the hard links that is not available for the soft links. This includes native view and forms generation for updating links.

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare/issues/1765

**Comment by cuahsimarko** [comment]
https://docs.google.com/document/d/1aYvFgOymrWJKv3cv8kkwXtOspdaGKSR40UgCdY4QNWU/edit?usp=sharing

**Comment by martinseul** [comment]
@alvacouch is this still relevant or has been resolved?

**Comment by alvacouch** [comment]
This issue is still relevant. The resource model remains inadequate to model constraints.

**Comment by martinseul** [comment]
@horsburgh @sblack-usu looking at this issue it looks like it could already be or will  be addressed as part of the DSAW/File based metadata project, if so we would not need to track it here as well and close it here as it is a fairly general issue, What do you think?

**Comment by horsburgh** [comment]
@martinseul - the work being done by @hyi using hsmodels instead of the Django models should address some of this issue by moving us closer to a file-based metadata management solution. But, I don't think her current work will entirely move us a way from the Django models and so it is probably a partial solution. @sblack-usu or @hyi can probably add more detail.

**Comment by hyi** [comment]
@martinseul I agree with @horsburgh. The metadata model will be still needed after my file-based metadata view/update work is completed and merged. We will have to remove all dependency to the metadata model in HydroShare including discovery before we can remove or greatly simplify the metadata model.

**Comment by martinseul** [comment]
Thanks @horsburgh and @hyi for your input. So part of the issue that is raised in here has been addressed but other parts need to be done, @hyi would it be possible to create a separate follow on issue describing what we need to do and close this one as it is very broad?

**Comment by hyi** [comment]
@martinseul Agreed, but I am looping in @alvacouch to get his input on this.

**Comment by eclark-cuahsi** [comment]
Closing per backlog review meeting on 6/9/22. in progress through other work.
