### ISSUE TITLE
Testing List for Issue #1900

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1935]
Please test the following items on https://park.hydroshare.org/. This test is to make sure that all the clickable elements (buttons, links etc) on the web page work as expected. 

#### Resource metadata creation and update
- [x] Time series resource  [Pabitra] @pkdash 
- [x] Generic resource [Tian] @gantian127
- [x] NetCDF resource [Tian] @gantian127
- [x] Raster resource [Tian] @gantian127
- [x] Web app resource [BYU] @zhiyuli
- [x] Collection resource [BYU] @zhiyuli
- [x] Ref time series resource [BYU] @zhiyuli
- [x] Script resource  [BYU] @zhiyuli
- [x] Model Instance[UVA] @mohamedmorsy 
- [x] Model program  [Tony] @Castronova @mohamedmorsy
- [x] MODFLOW Model Instance [UVA] @mohamedmorsy
- [x] SWAT Model Instance [UVA] @mohamedmorsy [creation, update, and new versions]
- [x] SWAT Model Instance [Purdue] @vmmerwade [apps]
- [x] File type and composite resource [Tian] @gantian127

#### Others Functionalities
- [x] Discovery [Zhaokun] @xuezhaokun 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS file upload [Hong] @hyi - there is no response when clicking login to irods, so it appears irods file upload is broken.
- [x] iRODS user account creation and deletion [Hong] @hyi - park is not federated with user zone, so the whole functionality for irods user account creation and deletion cannot be tested on park, however, when I clicked on "Delete your iRODS user account" link, a model dialog shows up asking me to confirm deletion as expected, but when I click "Confirm" button, nothing happens, and I have to click "Cancel" to get the dialog dismissed. It appears the event handler when clicking "Confirm" button is not invoked, so this appears to be broken as well.
- [x] Error info page: 400.html, 404.html, 500.html, 503.html [Hong] @hyi 
- [x] User profile page [Mauriel] @mauriel133
- [x] Group page [Mauriel] @mauriel133

**Comment by gantian127** [comment]
@mauriel133 I found that the arrow beside each "creator" and "contributor" seems not working. When I click on them, there is no response. I don't know if that is expected or not. Thanks
![image](https://cloud.githubusercontent.com/assets/5016511/23959545/1480730e-096b-11e7-9740-789b54388bcb.png)

**Comment by mauriel133** [comment]
@gantian127, are you clicking and dragging? These arrows are there only to indicate that the rows can be reordered by dragging and dropping. Perhaps it would be good to add a tooltip message.

**Comment by gantian127** [comment]
@mauriel133 The file type metadata editing for generic file type and raster file type don't work. When I edit any metadata within "File Metadata" tab and click on "Save changes", there is no response. This is not working as expected. 
![image](https://cloud.githubusercontent.com/assets/5016511/23960460/a96cc380-096d-11e7-8981-931af4b4d0b0.png)

**Comment by gantian127** [comment]
@mauriel133 The dragging and dropping works. I once thought the arrow is used for clicking. But if it is used for indication, that will be fine. If you want to add tooltip message, it may be better to let user know the dragging and dropping function. Thanks

**Comment by alexlemann** [comment]
@mjstealey are the submodules in the correct state for testing? What's the plan for updating ``hs_docker_base``?

**Comment by mauriel133** [comment]
@gantian127, I have found the problem and pushed a fix for the File Type metadata tab issue. I have started redeployment and will be ready for testing once it's finished.

**Comment by hyi** [comment]
@mauriel133 I have noted a couple of issues on the check list above regarding irods login and irods account creation and deletion from user profile page. There is no response once I clicked on the links. See above for details.

**Comment by gantian127** [comment]
@mauriel133 Thanks for the update. I think the "save changes" button works now. But the Key/Value extended metadata within the "File Metadata" tab doesn't work. Would you please have a look at it? Thanks
![image](https://cloud.githubusercontent.com/assets/5016511/23970392/33730e38-098f-11e7-8fd1-0122fa5fefac.png)

**Comment by mauriel133** [comment]
@gantian127, while fixing the Key/Value issue I found another error.

If I press the Enter key while adding keywords I get an error page: 
![image](https://cloud.githubusercontent.com/assets/2448568/24153424/0cf687c4-0e14-11e7-8d61-ea7cceb739d6.png)
![image](https://cloud.githubusercontent.com/assets/2448568/24153448/1ec09a94-0e14-11e7-91e3-a0192144d81f.png)

Also, these form elements share the same IDs with the ones in the main page. I suggest changing those to unique IDs.

**Comment by mauriel133** [comment]
@hyi, I looked into the issues you mentioned. I fixed a few things and the events seemed to trigger now.

 The error with the modal not being dismissed was caused by the ajax response returning an empty string error, thus not triggering the if clauses. See below:

![image](https://cloud.githubusercontent.com/assets/2448568/24162983/e1962cb8-0e2e-11e7-873e-5800307b1bb0.png)

I changed it so that the modal gets dismissed, but the empty string error should be checked in the back end as follow up.

**Comment by hyi** [comment]
@mauriel133 Thanks for debugging and finding this issue. I took a look at the backend code, and think this issue was caused by this line: https://github.com/hydroshare/hydroshare/blob/develop/theme/views.py#L348 where ex.message is empty for some reason. Can you change this line to the following 
```
dumps({"error": ex.message + ' - iRODS server failed to delete your iRODS account.'}),
```
so that the failure message will be shown even if exception message is empty? If this one line change at the back end indeed is the culprit for this issue, can you commit this one line change at the back end to your branch so that we don't have to create a separate issue to fix this? Thanks!

**Comment by hyi** [comment]
@mauriel133 If the line as mentioned above is indeed the culprit for causing this issue, can you make another one line change similarly at the back end for create_irods_account() as well to prevent similar issue for creating an irods account? Specifically, change this line:
https://github.com/hydroshare/hydroshare/blob/develop/theme/views.py#L379
to the following:
```
dumps({"error": ex.message + ' - iRODS server failed to create this iRODS account.'}),
```

**Comment by mauriel133** [comment]
@hyi, I have pushed this change. A few issues:

- This displays an error when the iRODS account creation fails in the Profile page, but a page refresh is issued right after and the message is only visible for a few seconds. We need to change the response in this case to not refresh the page.
- By looking at the code, we might have the same issue for errors when deleting iRODS accounts.

**Comment by hyi** [comment]
@mauriel133 Is the page refresh happened as a result of removing JavaScript inline event handlers? Since the request is made via AJAX, back end just returns success or error JSON response, so it is up to the front end to display the success or failure message and act accordingly. The old code just append success or failure message to irods-account-container div element without doing a page refresh. Can you check where the page refresh has happened as a result of new code changes?

**Comment by mauriel133** [comment]
@hyi, I disabled the page refresh at the end of this method. Although I'm still not sure what was causing it.

**Comment by mauriel133** [comment]
@zhiyuli, @mohamedmorsy, @Castronova, @vmmerwade, @xuezhaokun,

Coud you test the items in the checklist above and mark them if they are working as expected or report the issues here?'

**Comment by hyi** [comment]
@mauriel133 I just did a quick test and found no popup dialog is displayed when clicking "Browse iRODS..." button after being logged in. I remember it used to work, but I am not 100% sure now. If you want to reproduce this, you can check your hydroshare/local_settings.py file to find credential for hsproxy iRODS user account, and login via hsproxy credential, and then you should click on "Browse iRODS" button to reproduce this issue.

**Comment by zhiyuli** [comment]
@mauriel133 
I didn't see issues in testing. Sorry for the late response to this request.

**Comment by mauriel133** [comment]
@hyi, I fixed the issue with the modal window. You can test now.

**Comment by hyi** [comment]
@mauriel133 Did you redeploy your changes to park? I just checked on park and model dialog still does not show up when clicking on "Browse iRODS" button. I made sure I cleared up all browser cache to eliminate caching issue. So it looks like you may not have updated park? Anyway, it is still not working on park as of yet.

**Comment by mauriel133** [comment]
@hyi, I had not. I have started redeployment at park.hydroshare.org now.

**Comment by mauriel133** [comment]
All items have been checked. Closing.
