### ISSUE TITLE
List formatting is broken on a getting started help page

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3461]
https://help.hydroshare.org/introduction-to-hydroshare/getting-started/upload-data-and-models-and-share-with-others/

[004.zip](https://github.com/hydroshare/hydroshare/files/3335600/004.zip)

**Comment by martinseul** [comment]
Fixed on pages, @ndebuhr can you verify

**Comment by hydrocheck** [comment]
@martinseul The issue persists on Chrome:
1. Bullet 4 is offset by an image that should presumably be between bullets 3 and 4
2. Line spacing is not consistent across bullets.

![Screen Shot 2021-02-16 at 6 57 16 PM](https://user-images.githubusercontent.com/43424907/108136911-eb459080-7088-11eb-994a-d227eedc6d83.png)

**Comment by eclark-cuahsi** [comment]
Need to confirm if this issue still exists and either close or fix. Test in different browsers.
