### ISSUE TITLE
HTML entities in author names are not rendered properly on the resource page.

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3612]
Instead of displaying the symbol - for example the ' in O'Neal, the HTML entity string is displayed.

[004.zip](https://github.com/hydroshare/hydroshare/files/3692700/004.zip)

**Comment by alvacouch** [comment]
@martinseul @sblack-usu @hydrocheck Acknowledged. I know how it happened. We need to specifically HTML-encode things that are now utf-8 encoded. 

I made it possible in the most recent set of changes for these names to contain Unicode. Previously they could not and were limited to Ascii. The fix is to html-encode them rather than utf-8 encoding them. This is a broad issue in the UI and affects author names, abstracts, titles, and filenames.

**Comment by martinseul** [comment]
fixed

**Comment by martinseul** [comment]
@alvacouch @sblack-usu @hyi Still an issue i tested and behaviour is still the same and updating place name with ' fails as well

**Comment by alvacouch** [comment]
Yes, we still need to change the encoding before stuffing the data into an HTML form.

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/4070

**Comment by Castronova** [comment]
This has been resolved

**Comment by cuahsimarko** [comment]
This is not resolved, but covered by a separate ticket 
![image](https://user-images.githubusercontent.com/45397838/108850400-54f5fb00-75b1-11eb-8c88-7a74fde1dda6.png)
