### ISSUE TITLE
Geographic raster resource comments longer than 50 characters should be allowed

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#39]
Testing alpha.hydroshare.org version 1.2.1

I obtained the following error trying to create a resource.  Comments longer than 50 characters need to be allowed.
![p1](https://cloud.githubusercontent.com/assets/3456833/5604066/6ab4e2c2-9362-11e4-9949-dc257bde4cff.JPG)

**Comment by hyi** [comment]
This issue fixed and the fix pushed to AGU branch. Closing it for follow-up verification once it makes into alpha.

**Comment by hyi** [comment]
Reopen the issue and attach a "Ready to test" label as Dave suggested.

**Comment by dtarb** [comment]
This error still exists for method.  Please think through what the length of all fields should be.  50 characters is insufficient for method, just as it was insufficient for comment.

**Comment by hyi** [comment]
FIx pushed to github, pull request created to be merged into develop.

**Comment by dtarb** [comment]
Tested on development VM.  Both long methods and long comments now work.  Closing this issue.  There is a related issue #75 just opened related to gracefully handling all over limit user entries.
