### ISSUE TITLE
Eliminate inappropriate public exposure of emails

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#696]
Audit site for cases where email addresses are exposed publicly and resolve them.  

1. ~~email addresses should not be publicly displayed on profile~~
2. a messaging system should be used to send messages to other hydroshare users
3. a user should have the ability to set in their profile that messages they receive in hydroshare get forwarded to one of their registered email addresses.
4. ~~email addresses are part of the resourcemetadata.xml file downloadable when resources are downloaded for resource creators and contributors.  I submit that this not be changed.  This is equivalent to an email address appearing with the downloadable copy of a published paper, which is a common and accepted practice.~~

**Comment by hyi** [comment]
@dtarb I believe this issue has been resolved. Can you verify and see whether there are still issues with email exposure or not?

**Comment by dtarb** [comment]
Points 1 and 4 are OK.  Points 2 and 3 have still not been done.  I am OK to leave this on the backburner for now as we have higher priorities.

**Comment by mjstealey** [comment]
#1362 addresses messaging better and should be used for that thread
